# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'IMChartDemo' do
    use_frameworks!

    pod 'ReactiveCocoa', '2.5'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'Reveal-SDK', :configurations => ['Debug']

end
